import { IMAGES } from '../constants/images';

const review = (id, userName, rating, comment, createdAt) => ({
  id,
  userId: `seed-${id}`,
  userName,
  rating,
  comment,
  createdAt,
});

export const SEED_USERS = [
  {
    id: 'user-alicia',
    name: 'Alicia Ramírez',
    email: 'alicia@residente.com',
    password: 'demo1234',
    role: 'residente',
    phone: '3001112233',
    whatsapp: '3001112233',
    bio: 'Residente de Mistrató apasionada por el comercio local.',
    avatar: null,
    instagram: '',
    facebook: '',
  },
  {
    id: 'user-martha',
    name: 'Martha Cecilia Gutiérrez',
    email: 'martha@cafe.com',
    password: 'demo1234',
    role: 'emprendedor',
    phone: '3004567890',
    whatsapp: '3004567890',
    bio: 'Caficultora de tradición en las montañas de Mistrató. Café orgánico con orgullo local.',
    avatar: null,
    instagram: '@CafeDonaMartha',
    facebook: '@AromaDeMistrato',
    businessName: 'Café Doña Martha',
  },
  {
    id: 'user-carlos',
    name: 'Carlos Restrepo',
    email: 'carlos@turismo.com',
    password: 'demo1234',
    role: 'emprendedor',
    phone: '3102223344',
    whatsapp: '3102223344',
    bio: 'Guía turístico certificado en reservas de Mistrató.',
    avatar: null,
    instagram: '@TurismoMistrato',
    facebook: '@EcoTurismoMistrato',
    businessName: 'EcoTurismo Mistrató',
  },
  {
    id: 'user-jose',
    name: 'José Pineda',
    email: 'jose@artesanias.com',
    password: 'demo1234',
    role: 'emprendedor',
    phone: '3205556677',
    whatsapp: '3205556677',
    bio: 'Artesano en guadua con más de 20 años de experiencia en la región.',
    avatar: null,
    instagram: '@GuaduaMistrato',
    facebook: '@ArtesaniasJosePineda',
    businessName: 'Taller Guadua Mistrató',
  },
  {
    id: 'user-luis',
    name: 'Luis Torres',
    email: 'luis@motos.com',
    password: 'demo1234',
    role: 'emprendedor',
    phone: '3158889900',
    whatsapp: '3158889900',
    bio: 'Mecánico especializado en motocicletas con servicio a domicilio en todo el municipio.',
    avatar: null,
    instagram: '@TallerLuisTorres',
    facebook: '@MotosMistrato',
    businessName: 'Taller Torres',
  },
  {
    id: 'user-elena',
    name: 'Elena Rendón',
    email: 'elena@lacteos.com',
    password: 'demo1234',
    role: 'emprendedor',
    phone: '3124445566',
    whatsapp: '3124445566',
    bio: 'Productora de lácteos artesanales con leche de fincas locales.',
    avatar: null,
    instagram: '@LacteosElena',
    facebook: '@FincaLaEsperanza',
    businessName: 'Lácteos La Esperanza',
  },
  {
    id: 'user-julian',
    name: 'Julián Ocampo',
    email: 'julian@musica.com',
    password: 'demo1234',
    role: 'emprendedor',
    phone: '3187778899',
    whatsapp: '3187778899',
    bio: 'Músico y educador cultural dedicado a las tradiciones de Risaralda.',
    avatar: null,
    instagram: '@MusicaMistrato',
    facebook: '@CasaCulturaJulian',
    businessName: 'Academia Musical Julián',
  },
];

export const SEED_SERVICES = [
  {
    id: 'svc-cafe',
    entrepreneurId: 'user-martha',
    entrepreneurName: 'Martha Cecilia Gutiérrez',
    title: 'Café Orgánico de Mistrató',
    description:
      'Café 100% orgánico cultivado en las montañas de Mistrató. Venta por libra o arroba. Calidad premium directo del productor.',
    longDescription:
      'Nuestro Café Orgánico de Mistrató es el resultado de un proceso meticuloso que respeta el medio ambiente y exalta las notas dulces y frutales de la región.',
    category: 'agricultura',
    price: 15000,
    schedule: 'Lunes a Sábado: 7:00 AM - 5:00 PM',
    address: 'Calle 5 # 12-17, Barrio Quebrada Arriba',
    deliveryOptions: ['domicilio', 'local'],
    images: [IMAGES.cafeOrganico],
    reviews: [
      review('cafe-1', 'Alicia Ramírez', 5, 'El mejor café que he probado en Mistrató. Aroma increíble y sabor suave.', '2026-01-15T10:00:00.000Z'),
      review('cafe-2', 'Carlos M.', 5, 'Excelente calidad y atención. Lo recomiendo totalmente a la comunidad.', '2026-02-01T14:30:00.000Z'),
      review('cafe-3', 'Laura P.', 4, 'Muy buen producto local, fresco y con buen precio para la región.', '2026-02-20T09:15:00.000Z'),
      review('cafe-4', 'Pedro G.', 5, 'Entrega puntual y el café llegó recién tostado. Volveré a comprar.', '2026-03-10T16:00:00.000Z'),
    ],
    createdAt: '2025-11-01T08:00:00.000Z',
  },
  {
    id: 'svc-guia',
    entrepreneurId: 'user-carlos',
    entrepreneurName: 'Carlos Restrepo',
    title: 'Guía Turística Ecológica',
    description:
      'Recorridos por las cascadas y reservas naturales de Mistrató. Conoce la biodiversidad de nuestro municipio con guías locales.',
    longDescription:
      'Descubre los paisajes más hermosos de Mistrató con guías certificados y enfoque ecológico.',
    category: 'turismo',
    price: 45000,
    schedule: 'Fines de semana: 6:00 AM - 4:00 PM',
    address: 'Parque principal, Mistrató',
    deliveryOptions: ['local'],
    images: [IMAGES.guiaTuristica],
    reviews: [
      review('guia-1', 'María S.', 5, 'Carlos conoce cada rincón de las reservas. Una experiencia inolvidable para la familia.', '2026-01-20T11:00:00.000Z'),
      review('guia-2', 'Andrés V.', 4, 'Muy buen recorrido ecológico, solo sugiero llevar más agua en verano.', '2026-02-14T08:30:00.000Z'),
      review('guia-3', 'Diana L.', 5, 'Guía profesional, puntual y con gran conocimiento de la fauna local.', '2026-03-05T15:45:00.000Z'),
    ],
    createdAt: '2025-11-05T08:00:00.000Z',
  },
  {
    id: 'svc-artesanias',
    entrepreneurId: 'user-jose',
    entrepreneurName: 'José Pineda',
    title: 'Artesanías en Guadua',
    description:
      'Muebles y artesanías hechas con guadua local. Diseños personalizados que reflejan la cultura de Risaralda.',
    longDescription: 'Artesanías tradicionales en guadua con diseños personalizados.',
    category: 'artesanias',
    price: 80000,
    schedule: 'Lunes a Viernes: 8:00 AM - 6:00 PM',
    address: 'Vereda El Bosque, Mistrató',
    deliveryOptions: ['domicilio', 'local'],
    images: [IMAGES.artesaniasGuadua],
    reviews: [
      review('art-1', 'Rosa H.', 5, 'Un mueble de guadua hermoso y resistente. José cumplió el plazo acordado.', '2026-01-28T13:00:00.000Z'),
      review('art-2', 'Felipe T.', 4, 'Buena calidad artesanal, el diseño superó mis expectativas.', '2026-02-18T10:20:00.000Z'),
      review('art-3', 'Carmen R.', 5, 'Apoyar el talento local vale la pena. Recomiendo sus canastos decorativos.', '2026-03-02T17:10:00.000Z'),
      review('art-4', 'Jorge M.', 5, 'Atención personalizada y precios justos para piezas hechas a mano.', '2026-03-22T09:00:00.000Z'),
    ],
    createdAt: '2025-11-10T08:00:00.000Z',
  },
  {
    id: 'svc-motos',
    entrepreneurId: 'user-luis',
    entrepreneurName: 'Luis Torres',
    title: 'Reparación de Motos',
    description:
      'Taller mecánico especializado en motos. Servicio a domicilio disponible en todo Mistrató. 15 años de experiencia.',
    longDescription: 'Mantenimiento y reparación de motocicletas con garantía.',
    category: 'servicios',
    price: 35000,
    schedule: 'Lunes a Sábado: 7:30 AM - 6:00 PM',
    address: 'Carrera 4 # 8-20, Centro',
    deliveryOptions: ['domicilio'],
    images: [IMAGES.reparacionMotos],
    reviews: [
      review('mot-1', 'Santiago P.', 5, 'Luis arregló mi moto en el día y el precio fue transparente. Muy confiable.', '2026-02-05T12:00:00.000Z'),
      review('mot-2', 'Paola N.', 4, 'Buen servicio a domicilio, la moto quedó funcionando perfecta.', '2026-02-25T14:30:00.000Z'),
      review('mot-3', 'Miguel A.', 5, 'Llevo años confiando en este taller. Siempre honesto con los repuestos.', '2026-03-15T11:15:00.000Z'),
    ],
    createdAt: '2025-11-12T08:00:00.000Z',
  },
  {
    id: 'svc-lacteos',
    entrepreneurId: 'user-elena',
    entrepreneurName: 'Elena Rendón',
    title: 'Lácteos Caseros Artesanales',
    description:
      'Servicio de venta de quesos, yogurt y mantequilla artesanal. Elaborados frescos con leche de vacas de la región.',
    longDescription: 'Productos lácteos artesanales de la más alta calidad.',
    category: 'alimentos',
    price: 12000,
    schedule: 'Diario: 6:00 AM - 4:00 PM',
    address: 'Finca La Esperanza, vía vereda La Linda',
    deliveryOptions: ['domicilio', 'local'],
    images: [IMAGES.lacteosCaseros],
    reviews: [
      review('lac-1', 'Lucía F.', 5, 'El queso campesino es delicioso, sabe como el de antes en el pueblo.', '2026-01-10T07:30:00.000Z'),
      review('lac-2', 'Héctor B.', 4, 'Yogurt natural muy fresco, pedimos entrega los sábados sin problema.', '2026-02-12T08:00:00.000Z'),
      review('lac-3', 'Isabel C.', 5, 'Productos artesanales de verdad, se nota la calidad de la leche local.', '2026-03-08T13:40:00.000Z'),
      review('lac-4', 'Roberto D.', 5, 'Elena es muy amable y los precios son accesibles para la comunidad.', '2026-03-28T10:00:00.000Z'),
    ],
    createdAt: '2025-11-15T08:00:00.000Z',
  },
  {
    id: 'svc-musica',
    entrepreneurId: 'user-julian',
    entrepreneurName: 'Julián Ocampo',
    title: 'Clases de Música',
    description:
      'Clases de guitarra, flauta y canto. Rescatamos las tradiciones musicales de Mistrató para todas las edades.',
    longDescription: 'Formación musical para niños, jóvenes y adultos.',
    category: 'educacion',
    price: 25000,
    schedule: 'Martes y Jueves: 3:00 PM - 7:00 PM',
    address: 'Casa de la Cultura, Mistrató',
    deliveryOptions: ['local'],
    images: [IMAGES.clasesMusica],
    reviews: [
      review('mus-1', 'Valentina G.', 5, 'Mi hija aprendió guitarra en pocas semanas. Julián tiene mucha paciencia.', '2026-02-01T16:00:00.000Z'),
      review('mus-2', 'Oscar R.', 4, 'Clases de canto muy dinámicas, ambiente familiar y acogedor.', '2026-02-20T18:30:00.000Z'),
      review('mus-3', 'Natalia P.', 5, 'Rescata la música tradicional del municipio. Totalmente recomendado.', '2026-03-12T15:00:00.000Z'),
    ],
    createdAt: '2025-11-18T08:00:00.000Z',
  },
];

export function getSeedState() {
  return {
    users: SEED_USERS,
    services: SEED_SERVICES,
    session: null,
  };
}
